---
galaxy_info:
  author: Thomas Wiest
  description: Adds the twiest user and group
  company: MTK-Hub
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - system
dependencies: []
