# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

alias go=gnome-open
alias vi=vim
alias pssh='pssh -t 0'
alias tree='tree -A'

# gpa
source ~/code/li-ops/misc/gpa.sh


export EDITOR=vim

if [ -f /usr/share/git-core/contrib/completion/git-prompt.sh ]
then
    source /usr/share/git-core/contrib/completion/git-prompt.sh

    export GIT_PS1_SHOWDIRTYSTATE=true
    export GIT_PS1_SHOWUNTRACKEDFILES=true
    export GIT_PS1_SHOWSTASHSTATE=true
    export GIT_PS1_SHOWUPSTREAM="auto"

    export PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
fi
