set nocompatible
"set nu
"set tabstop=2
"set shiftwidth=2
"set softtabstop=2
set ai
set guifont=Courier:h10
"set expandtab
set smarttab
set ignorecase
let g:rubycomplete_rails = 1

set tabstop=4
set shiftwidth=4
set expandtab
set list

"flag problematic whitespace (trailing and spaces before tabs)
"Note you get the same by doing let c_space_errors=1 but
"this rule really applies to everything.
highlight RedundantSpaces term=standout ctermbg=red guibg=red
match RedundantSpaces /\s\+$\| \+\ze\t/ "\ze sets end of match so only spaces highlighted
"use :set list! to toggle visible whitespace on/off
set listchars=tab:>-,trail:.,extends:>
:let mapleader = "-"
