---
galaxy_info:
  author: Thomas Wiest
  description: Container server related tasks
  company: MTK
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - system
dependencies: []
